//! Everything both tiers must agree on byte-for-byte.
//!
//! The schema, the id newtypes, the state enums, the port allocator, the metric names and the
//! room-probe contract live here. Filesystem and Kubernetes code deliberately do not: see the
//! dependency note in `Cargo.toml`.

pub mod artifact;
pub mod config;
pub mod db;
pub mod hash;
pub mod ids;
pub mod metrics;
pub mod model;
pub mod secret;

// Generated by `diesel print-schema` and checked in; CI asserts it matches the migrations.
// See diesel.toml for how to regenerate.
#[rustfmt::skip]
pub mod schema;

/// Build identity, shared by every binary so `--version` means the same thing everywhere.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Embedded migrations, run by the orchestrator only.
///
/// The orchestrator is a singleton holding a leader lock, so it is the natural migrator. The
/// lobby runs `run_pending_migrations` from every one of its replicas, which is a race it has
/// been lucky with; Puna's web tier asserts the schema is current and fails readiness instead,
/// so a web pod rolled out ahead of the orchestrator stays NotReady rather than serving against
/// a schema it does not understand.
pub const MIGRATIONS: diesel_migrations::EmbeddedMigrations =
    diesel_migrations::embed_migrations!("./migrations/");

// Role and Environment live in `config` alongside the rest of the startup inputs; re-exported
// here because they are referenced constantly and `puna_core::Role` reads better than
// `puna_core::config::Role`.
pub use config::{CommonConfig, Environment, OrchestratorConfig, Role};
